# seo
seo_des: Colorful，一个骚年路过这里，与你一起探讨关于前端技术，设计，Hack的奥秘。
seo_keyword: COLORFUL, Colorful, colorful, Archer, archer, 小A, 前端博客，前端工程师

# site
site_domain: http://xiaoa.name

# github plugins
gems:
  - jekyll-mentions
  - jemoji
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# blog global settings
name: COLORFUL
description: 有个骚年路过这里

# highlighter & markdown
# use default
# highlighter: pygments
kramdown:
  input: GFM

# reading settings
exclude: ["node_modules", "gulpfile.js", "README.md", "package.json", "dist"]

# author
author:
  name: Archer
  email: qddegtya@gmail.com
  github: qddegtya

# jekyll settings
excerpt_separator: <!-- more -->
permalink: /blog/:year/:month/:day/:title/
baseurl: ""

# pagination
paginate: 8
paginate_path: "blog/page:num"

# jekyll-archives
jekyll-archives:
  enabled: ["year", "tags", "categories"]
  layouts:
    tag: tag
    year: year
    category: category
  permalinks:
    year: '/blog/archives/:year/'
    tag: '/blog/tags/:name/'
    category: '/blog/categories/:name/'

# Friends
friends: [
    {
        title: "",
        href: ""
    }
]
