# seo
seo_des: Colorful，一个骚年路过这里，与你一起探讨关于前端技术，设计，Hack的奥秘。
seo_keyword: COLORFUL, Colorful, colorful, Archer, archer, 小A, 前端博客，前端工程师

# site
site_domain: http://xiaoa.name

# cdn domain
cdn_domain: http://7xqy7v.com1.z0.glb.clouddn.com/

# github plugins
gems:
  - jekyll-mentions
  - jemoji
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# blog global settings
name: COLORFUL
description: 有个骚年路过这里

# highlighter & markdown
# use default
# highlighter: pygments
# Github now use jekyll 3.0

# reading settings
exclude: ["node_modules", "gulpfile.js", "README.md", "package.json", "dist"]

# author
author:
  name: Archer
  email: qddegtya@gmail.com
  github: qddegtya

# jekyll settings
excerpt_separator: <!-- more -->
permalink: /blog/:year/:month/:day/:title/
baseurl: ""

# pagination
paginate: 8
paginate_path: "blog/page:num"

# jekyll-archives
jekyll-archives:
  enabled: ["year", "tags", "categories"]
  layouts:
    tag: tag
    year: year
    category: category
  permalinks:
    year: '/blog/archives/:year/'
    tag: '/blog/tags/:name/'
    category: '/blog/categories/:name/'

# follows
follows: [
  {
    title: "稀土掘金",
    url: "http://gold.xitu.io/#/user/564596b360b25b79f069ad76",
    ico: "http://gold.xitu.io/favicon.ico"
  },{
    title: "GITHUB",
    url: "https://github.com/qddegtya",
    ico: "https://github.com/favicon.ico"
  },{
    title: "微博",
    url: "http://weibo.com/IMArcher",
    ico: "http://weibo.com/favicon.ico"
  },{
    title: "CODING",
    url: "https://coding.net/u/archer",
    ico: "https://coding.net/favicon.ico"
  },{
    title: "开源中国",
    url: "http://my.oschina.net/Archerminia",
    ico: "http://oschina.net/favicon.ico"
  },{
    title: "知乎",
    url: "https://www.zhihu.com/people/archer_xiaoa",
    ico: "https://www.zhihu.com/favicon.ico"
  }
]

# Friends
friends: [
  {
    title: "鲍勃の部屋",
    url: "http://jiafeifei.weebly.com/",
    ico: "http://www.xiaoa.name/favicon.ico"
  },{
    title: "zixin’s blog",
    url: "http://zixiinlian.github.io/",
    ico: "http://www.xiaoa.name/favicon.ico"
  },{
    title: "Kyonko记录站",
    url: "http://kyon-df.com/",
    ico: "http://www.xiaoa.name/favicon.ico"
  },{
    title: "Kiven",
    url: "http://www.mrkiven.name/",
    ico: "http://www.mrkiven.name/public/favicon.ico"
  }
]

# Skills
skills: [
  {
    skill: "HTML",
    dur: "36",
    score: "85",
    color: "#16a085"
  },{
    skill: "CSS",
    dur: "36",
    score: "75",
    color: "#27ae60"
  },{
    skill: "Javascript",
    dur: "36",
    score: "85",
    color: "#2980b9"
  },{
    skill: "Python",
    dur: "24",
    score: "75",
    color: "#8e44ad"
  },{
    skill: "Git",
    dur: "24",
    score: "70",
    color: "#2c3e50"
  },{
    skill: "Linux/Mac",
    dur: "24",
    score: "70",
    color: "#f39c12"
  },{
    skill: "Nodejs",
    dur: "24",
    score: "70",
    color: "#c0392b"
  }
]
