# seo
seo_des: Colorful，一个骚年路过这里，与你一起探讨关于前端技术、设计、Hack 的魔法。
seo_keyword: COLORFUL, Colorful, colorful, Archer, archer, 小 A, 前端博客，前端工程师

# site
url: https://xiaoa.name

# github plugins
plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# blog global settings
name: COLORFUL
description: 有个骚年路过这里

# highlighter & markdown
# use default
# highlighter: pygments
# Github now use jekyll 3.0

# reading settings
exclude: ["node_modules", "gulpfile.js", "README.md", "package.json", "dist"]

# author
author:
  name: Archer
  email: qddegtya@gmail.com
  github: qddegtya

# jekyll settings
excerpt_separator: <!-- more -->
permalink: /blog/:year/:month/:day/:title/
baseurl: ""

# pagination
paginate: 8
paginate_path: "blog/page:num"

# jekyll-archives
jekyll-archives:
  enabled: ["year", "tags", "categories"]
  layouts:
    tag: tag
    year: year
    category: category
  permalinks:
    year: '/blog/archives/:year/'
    tag: '/blog/tags/:name/'
    category: '/blog/categories/:name/'

# follows
follows: [
  {
    title: "语雀",
    url: "https://www.yuque.com/chiyu-heb0t",
    ico: "https://gw.alipayobjects.com/zos/rmsportal/UTjFYEzMSYVwzxIGVhMu.png"
  },{
    title: "稀土掘金",
    url: "https://juejin.cn/user/1926000099465214",
    ico: "https://juejin.cn/favicon.ico"
  },{
    title: "Segmentfault",
    url: "https://segmentfault.com/u/xiaoa",
    ico: "https://static.segmentfault.com/main_site_next/e3057aed/favicon.ico"
  },{
    title: "Github",
    url: "https://github.com/qddegtya",
    ico: "https://github.com/favicon.ico"
  },{
    title: "知乎",
    url: "https://www.zhihu.com/people/archer_xiaoa",
    ico: "https://www.zhihu.com/favicon.ico"
  }
]

# Friends
friends: [
  {
    title: "鲍勃の部屋",
    url: "https://jiafeifei.weebly.com/",
    ico: "https://xiaoa.name/favicon.ico"
  },{
    title: "zixin’s blog",
    url: "https://zixiinlian.github.io/",
    ico: "https://xiaoa.name/favicon.ico"
  }
]

# Skills
skills: [
  {
    skill: "HTML",
    dur: "120",
    score: "95",
    color: "#16a085"
  },{
    skill: "CSS",
    dur: "120",
    score: "75",
    color: "#27ae60"
  },{
    skill: "Javascript",
    dur: "120",
    score: "95",
    color: "#2980b9"
  },{
    skill: "Python",
    dur: "48",
    score: "85",
    color: "#8e44ad"
  },{
    skill: "Git",
    dur: "120",
    score: "80",
    color: "#2c3e50"
  },{
    skill: "Linux/Mac",
    dur: "120",
    score: "80",
    color: "#f39c12"
  },{
    skill: "Nodejs",
    dur: "60",
    score: "90",
    color: "#c0392b"
  }
]
